### ISSUE TITLE
[Bug] Appearing since 2-3 days ago - box jumping around screeen (GIF included)

### ISSUE THREAD

**Issue by Nick2bad4u** [cvzi/Metacritic-userscript#24] opened 2023-09-15 15:13 UTC
https://i.gyazo.com/d218fcaf4f6043aef8e4ea162d7de57c.mp4

**Comment by cvzi** [comment] 2023-09-15 18:45
Can you try to update to the newest version and see if the problem persists?

Duplicate of #23

**Closed by cvzi** 2023-09-15 18:45 UTC

**Comment by Nick2bad4u** [comment] 2023-09-16 16:27
> Can you try to update to the newest version and see if the problem persists?
> 
> Duplicate of #23

Fixed. Thanks!

**Comment by cvzi** [comment] 2023-09-16 22:33
Thanks for the feedback!
