### ISSUE TITLE
Doesn't work on IMDb

### ISSUE THREAD

**Issue by al1ydn** [cvzi/Metacritic-userscript#21] opened 2023-08-18 08:53 UTC
I have to click Search now for and remove the rating and genres to find the movie every time. For example:

The Prestige  ⭐ 8.5 | Drama, Mystery, Sci-Fi

**Comment by cvzi** [comment] 2023-08-18 14:10
Actually #22 didn't fix it.

The problem is that it depends on the language of the browser and the selected language on imdb page.

Example:
https://www.imdb.com/title/tt0847880/

| language | Title | Original title |
| --- | --- | --- |
| `en-US` | Cargo 200 | Gruz 200 |
| `es-ES` | Gruz 200 | - |
| `ru-RU` | Груз 200 | Gruz 200 |

But Metacritic (https://www.metacritic.com/movie/cargo-200) is always in English, so we need `Cargo 200` to find it

**Comment by cvzi** [comment] 2023-08-18 14:25
I'll fix it later today.

**Comment by cvzi** [comment] 2023-08-18 19:51
Should be fixed now

**Closed by cvzi** 2023-08-18 19:51 UTC

**Comment by al1ydn** [comment] 2023-08-19 01:02
Fixed, thank you.

A small notice: When clicked Search now, the text field appears empty. It doesn't contain movie title.
